// flow-typed signature: 5bccd7202d09d1cff768a897056d6f9a
// flow-typed version: <<STUB>>/typeface-roboto_v^0.0.43/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
